{% set provider = "aws" %}
{% set version = "1.33.0" %}

{% set name = "terraform-provider-" + provider %}
{% set x4_plugin = name + '_v' + version + "_x4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: src/github.com/terraform-providers/{{ name|lower }}
    url: https://github.com/terraform-providers/{{ name }}/archive/v{{ version }}.tar.gz  # [not win]
    sha256: e38ffe8d5089c880c1227c002826865a398df30f820d99e36e245bd0c62c7618  # [not win]

    url: https://releases.hashicorp.com/{{ name }}/{{ version }}/{{ name }}_{{ version }}_windows_amd64.zip  # [win64]
    sha256: 990ad78e2f378feddef6c3a1143b31776acb2b6d29c10412739b4d9d7daf8bb2  # [win64]

build:
  number: 1000
  script:
    - XCOPY src\github.com\terraform-providers\{{ name|lower }}\{{ x4_plugin }}.exe %LIBRARY_BIN%  # [win]

requirements:
  build:
    - {{ compiler('go') }}  # [not win]
    - make  # [not win]
  run:
    - terraform >=0.10

test:
  commands:
    - echo 'provider "{{ provider }}" { version="{{ version }}" }' > init.tf  # [not win]
    - test $(terraform init | grep -c 'Downloading') = 0  # [not win]

about:
  home: https://www.terraform.io
  license: MPL 2.0
  summary: The Terraform AWS provider
  doc_url: https://www.terraform.io/docs/providers/{{ provider }}/index.html
  dev_url: https://github.com/terraform-providers/{{ name }}

extra:
  recipe-maintainers:
    - sodre
