{% set provider = "aws" %}
{% set version = "1.31.0" %}

{% set name = "terraform-provider-" + provider %}
{% set x4_plugin = name + '_v' + version + "_x4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: src/github.com/terraform-providers/{{ name|lower }}
    url: https://github.com/terraform-providers/{{ name }}/archive/v{{ version }}.tar.gz  # [not win]
    sha256: 2638fb82368fdfc1e4c8fc13342449b5d5089b4ac278d8a479e342f7aba252b3  # [not win]

    url: https://releases.hashicorp.com/{{ name }}/{{ version }}/{{ name }}_{{ version }}_windows_amd64.zip  # [win64]
    sha256: ef1d6768f2e4cddd5f626f81c4cddc0c7017e6e42ecd66210b6c087151534573  # [win64]

build:
  number: 0
  script:
    - XCOPY src\github.com\terraform-providers\{{ name|lower }}\{{ x4_plugin }}.exe %LIBRARY_BIN%  # [win]

requirements:
  build:
    - {{ compiler('go') }}  # [not win]
    - make  # [not win]
  run:
    - terraform >=0.10

test:
  commands:
    - echo 'provider "{{ provider }}" { version="{{ version }}" }' > init.tf  # [not win]
    - test $(terraform init | grep -c 'Downloading') = 0  # [not win]

about:
  home: https://www.terraform.io
  license: MPL 2.0
  summary: The Terraform AWS provider
  doc_url: https://www.terraform.io/docs/providers/{{ provider }}/index.html
  dev_url: https://github.com/terraform-providers/{{ name }}

extra:
  recipe-maintainers:
    - sodre
