{% set provider = "aws" %}
{% set goname = "github.com/terraform-providers/terraform-provider-"+provider.lower() %}
{% set version = "1.33.0" %}

{% set name = goname.split('/')[-1] %}
{% set pkg_src = ('src/'+goname).replace("/",os.sep) %}

{% set x4_plugin = name + '_v' + version + "_x4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder:  {{ pkg_src }}
    url: https://{{ goname }}/archive/v{{ version }}.tar.gz
    sha256: e38ffe8d5089c880c1227c002826865a398df30f820d99e36e245bd0c62c7618

build:
  number: 1000
  script:
    - pushd {{ pkg_src }}
    - go build -v -o $GOBIN/{{ x4_plugin }} .  # [unix]
    - go build -v -o %GOBIN%\{{ x4_plugin }}.exe .  # [win]

requirements:
  build:
    - {{ compiler('go') }} >=1.11.3
  run:
    - terraform >=0.10

test:
  requires:
    - m2-grep       # [win]
    - m2-coreutils  # [win]
  commands:
    - bash -euf -c "echo 'provider \"{{ provider|lower }}\" { version=\"{{ version }}\" }' > init.tf"
    - terraform init > init.out
    - bash -euf -c "test $(grep -c Downloading init.out) = 0"

about:
  home: https://www.terraform.io
  license: MPL 2.0
  summary: The Terraform AWS provider
  doc_url: https://www.terraform.io/docs/providers/{{ provider }}/index.html
  dev_url: https://github.com/terraform-providers/{{ name }}

extra:
  recipe-maintainers:
    - sodre
