travis:
  secure:
    BINSTAR_TOKEN: ZqytZQ6g75H/p1yXF+B0MPIAGcsb/l7a1ba8YF3pGZsp1EC8gcJx2PG6med7jb26CHv3OQGb4Fd4NXo7CCAbyfF9byaD2h7FiaZ3kj68ySHUj5KxtyoU5+NdrhU6OnYUPtnv+CxNThzq/eDx0kiUHFy0U4wKMgzNN4mR8JUTp8gm/TdrNqAOad+VueO/icn0EBi4iCbOhR7LPncMghOFxQ9V03+r1z5/cGk1juXcPVVa6E9fDim4UZ4BpCCQnaF6NKZMwFNhIi9Asbz2xOlKw5us+xpZF+VE3bdCVQRjpjdA1nrY1JtWFWd+7U5c3ggkjSyM5b98LKhW2AlfUiMCs7KD0Nmek3EN97fodoYLwT6qMEyhPii84vktwjpkTtbj4wMf2xfXlCX8dIabxUSmAtSmWOiwebEq3rcb78ZIx/TC+IR8FQ1+YZB+5ArSuQ0h+7AHgXZguQzdA7T0thJQPhb9hBzabo8M5sOmenu6T7HwzGDJEiIp1IhHPp0ysgzgQhVWSQg2UVKSWmREfxEHvxqeJeQWPxCXXceKGC5Zp/gPj5NW/6heikEKTrUIpHmlQuCf2swY2SkIew/L6GfihYQqOOdOOxrDvVQUjTlf7Zdgdl+SLn/Ba7VGjgPZSUmyAlI2R949y3N6F6GKXG1Mou/ZAlyP6SdqixwLkouo/9M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
